Require Cropper library in `componentDidMount` method
For build `react-cropper` for server bundler by `webpack`, I've got:

```
ReferenceError: window is not defined
    at Object.defineProperty.value (**/node_modules/cropperjs/dist/cropper.js:1219:18)
```

I propose this refactoring according sokra (creator of webpack) comment:
https://github.com/webpack/react-starter/issues/37#issuecomment-93943419